### ISSUE TITLE
Is There any way to download full list of blocked domain 

### ISSUE THREAD

**Issue by IRSHADPM** [CodeKJ/DISIFY#10]
Thank you for providing this API.
 Is There any API to get full list of blocked domain ?, we would like to get the list of blocked email domain so that we can validate email from our own instead of calling this API for all email validation.

**Comment by citronkaste** [comment]
Hi,

There are links available to blacklists in website menu and footer.

Domain blacklist: https://disify.com/blacklist/domains
MX blacklist: https://disify.com/blacklist/mx

**Comment by IRSHADPM** [comment]
Thank you so much for your quick response.
It help us to get all the list of blocked domains. to maintain the data we would like to get the new list of  blacklisted domains  and domains removed from the blackList weekly. is there any API available for this requirement.  

could you please give an idea what is MX blacklist ?
Thanks in advance.

**Comment by citronkaste** [comment]
Just use links I provided, both lists are automatically updated. There are blacklist updates on average few times per month.
You can call those links as API, extract content (explode by new-line) and you are good to go.

MX is part of DNS records for specific domain.
How its useful in our case? Let me give you an example.
1) Lets say disposable email provider has 3 domains available: domain1.com, domain2.com, domain3.com
2) Our blacklist would contain domain1.com and domain2.com, but wouldn't yet have included domain3.com, and in theory should return that it isn't disposable? Well, not in our case - not so easy to fool our API. Here is why.
3) As long as we have blocked this provider by its MX records, we automatically can detect that domain3.com is also disposable, because it contains MX records which we have blacklisted.

You can use this tool to test and see MX records for domains: https://mxtoolbox.com/

Also you can use this MX blacklist in your own code, for example in PHP there are this function (also used in Disify): https://www.php.net/manual/en/function.getmxrr.php

DISIFY has following validations, by steps:
1) Check if format is valid (email or domain)
2) Check if domain is listed in blacklist
3) Check if hostname has DNS records (response)
4) Check if hostname has MX records OR at least single A record.
5) Check if these MX records are listed in our blacklist

**Comment by IRSHADPM** [comment]
Thank you so much for providing this information.
