### ISSUE TITLE
Data Sharing Concerns?

### ISSUE THREAD

**Issue by dphillipsatzipline** [CodeKJ/DISIFY#2]
Are the e-mail addresses that are sent in, stored anywhere? Is there any type of terms and conditions users of your API are agreeing to?

**Comment by citronkaste** [comment]
Hi.

Domain part is stored, yes. Purely for statistics/analytics. Nothing is being leaked or shared elsewhere.
If you are concerned about privacy you can always use "domain" end-point. Currently it uses same validation methods as using "email" end-point. In future I plan to implement additional check for SMTP response, and it will require mailbox of course, but this feature probably will be available through account registration and some limitations - because providing such service for free can easily lead my API to be blacklisted for some email providers.

Regarding terms and conditions. There are none for currently available free API, you can use it however you want. However, I am monitoring API traffic and any suspicious requests might be blocked without warning.

**Comment by dphillipsatzipline** [comment]
Is the source code available for us to host this on our own?

**Comment by citronkaste** [comment]
In future I might share source for some validation methods used, so you can implement it yourself. But don't expect project code to be publicly available, I plan to extend it with other services and would like to keep it as my intellectual property.

**Comment by dphillipsatzipline** [comment]
Can you share the validation methods you used?

**Comment by citronkaste** [comment]
Not atm. I need to prepare it first, its not something I can simply copy/paste. I will make separate documentation with all API methods, functionality and back-end source for some validations used.
