### ISSUE TITLE
Database updated on daily basis ?

### ISSUE THREAD

**Issue by blackarcanis** [CodeKJ/DISIFY#6]
Hi !
Thank you for the great job you did there :)

The context:  yesterday you have returned as non valid this domain => "@live.com.mx" 
But today I tried it again and it was accepted (and you are right, it should be).

So my question is => when are you updating your database and how ?

**Comment by citronkaste** [comment]
Hi.

This is valid domain. I checked logs and this looks like to be an error caused by temporary unavailable blacklist (failed to load blacklist), which have resulted in disposable response. I will check in more details what could have caused it. And probably patch it, so in future in case of blacklist failure it's not forced as disposable response.

About blacklist updates overall. On working days I rarely do updates (with exceptions on some issues), mostly on weekends I process submissions, and monthly reviewing/researching new disposable email providers.

**Comment by blackarcanis** [comment]
> in case of blacklist failure it's not forced as disposable response.

That would be perfect yes :) That was probably the error and why after that on our side we have rejected this email.

Good to know for the update. Thank you so much to doing this !
